package com.labweb.agrodoa_backend.model.enums;

public enum TipoNotificacao {
    ANUNCIO_VALIDADE_PROXIMA,
    ANUNCIO_LIMITE_NEGOCIANTES,
    USUARIO_RECEBEU_DENUNCIA,
    USUARIO_ATINGIU_LIMITE_DENUNCIAS,
    CAUSA_PRAZO_FINAL,
    CAUSA_META_ATINGIDA,
    AVISO_INTERNO_SISTEMA,
    NEGOCIACAO_FINALIZADA,
    ANUNCIO_STATUS_ALTERADO
}
